### ISSUE TITLE
Set TOU Charge occasionally not working

### ISSUE THREAD

**Issue by SimonJBurley** [666djb/solarpi#4]
Firstly; many thanks for solarpi. It's working with my SPH 3600 (configured as SPH 3000 in solarpi) and is so much better than using Growatt's mobile app and website.
I am on Octopus' Intelligent Go and have set Home Assistant automation to use TOU charging when a cheap slot is active. Sometimes (~5%) the TOU charging fails to become enabled or disabled correctly; leaving the battery not charging when it should be or still in a charging state when it should be load first.
I leave the inverter with TOU charging time 1 set to 00:00 - 23:59 and simply set Charge 1 Enable appropriately and press "Set TOU charge" with automation. From Home Assistant's logbook, this seems to run even though, occasionally, the inverter's state is not changed.

From the solarpi journal, I can see a failure this morning

```
Oct 23 05:33:54 raspberrypi npm[582]: 23/10/2023, 5:33:54 BST Control values stored
Oct 23 05:33:54 raspberrypi npm[582]: 23/10/2023, 5:33:54 BST Publishing data
Oct 23 05:33:55 raspberrypi npm[582]: 23/10/2023, 5:33:55 BST Received Set TOU Charging command
Oct 23 05:34:45 raspberrypi npm[582]: 23/10/2023, 5:34:45 BST Error sending command to inverter:  Transacti>
Oct 23 05:34:45 raspberrypi npm[582]:   name: 'TransactionTimedOutError',
Oct 23 05:34:45 raspberrypi npm[582]:   message: 'Timed out',
Oct 23 05:34:45 raspberrypi npm[582]:   errno: 'ETIMEDOUT'
Oct 23 05:34:45 raspberrypi npm[582]: }
```
Is this likely cabling or the inverter being difficult?

**Comment by 666djb** [comment]
Hi!

I use Octopus Intelligent and have Home Assistant use TOU Charging when I get a cheap slot too, I do it in a slightly different way to you but it does work with 100% success, however, that is not likely the cause of your problem. I suspect that the Transaction Timed Out Error is more likely a cable problem (I did see those errors in early days of testing before I used a method in my code to ensure that it was not possible to send a command to the inverter while still waiting for a response from the previous).

I wonder whether there are any journal entries immediately prior to 05:33:54 that are relevant?

I could write something that retries a command if a Timed Out Error is received - I'll put that in the list of things to do.

As a stop gap, you could add to your Home Assistant automation a short delay (say 10 seconds) and then repeat the action of pressing the TOU Charge set button.

For completeness, here is my Octopus Intelligent automation:
```
alias: Octopus Intelligent Slot
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.octopus_intelligent_slot
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.octopus_intelligent_slot
    to: "off"
condition: []
action:
  - if:
      - condition: state
        entity_id: binary_sensor.octopus_intelligent_slot
        state: "on"
    then:
      - service: number.set_value
        data:
          value: "0"
        target:
          entity_id: number.solarpi_tou_charge_2_start_hour
      - service: number.set_value
        data:
          value: "0"
        target:
          entity_id: number.solarpi_tou_charge_2_start_minute
      - service: number.set_value
        data:
          value: "23"
        target:
          entity_id: number.solarpi_tou_charge_2_stop_hour
      - service: number.set_value
        data:
          value: "59"
        target:
          entity_id: number.solarpi_tou_charge_2_stop_minute
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.solarpi_tou_charge_2_enable
    else:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.solarpi_tou_charge_2_enable
  - service: button.press
    data: {}
    target:
      entity_id: button.solarpi_tou_charge_set
mode: single
```

This is triggered by either the Intelligent Slot changing to On or Off (this helps deal with that value becoming Unavailable if there is an outage with the Octopus API). Then if the Intelligent Slot is On, it sets up the times from 00:00 to 23:59 on TOU Charge Slot 2 and enables that TOU Charge slot, else (if the Intelligent Slot is Off) it disables that TOU Charge slot. Then, finally it presses the TOU Charge set button (to send the command and write the values to the inverter). (I have a slightly more complex version of this automation that turns off/on a TOU Discharge slot too as I am playing with having any excess charge in the battery exported in the run up to my regular Octopus Intelligent 23:30-05:30 charging slot)

You might be interested in a new entity I have added in the v1.0.8 release - this receives a text value back from SolarPi to report whether a command was successful or not. This too could be used in an automation to do something if there was a problem sending a command. I added this recently when I noticed how the Growatt Inverter behaves if you set overlapping TOU Charge and TOU Discharge time slots, it simply says "nope, you can't do that".


![image](https://github.com/666djb/solarpi/assets/52598873/9eacb22c-a28f-49c4-8957-a4ea780e565e)
